# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'dConnectDevicePebble' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  pod 'PebbleKit-Static'
  pod 'DeviceConnectSDK', podspec: '../../dConnectSDK/dConnectSDKForIOS/DeviceConnectSDK.podspec'

end
