# source 'https://github.com/DeviceConnect/DeviceConnect-PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
$targetSource = "https://github.com/TakayukiHoshi1984/DeviceConnect-iOS"
platform :ios, '9.0'
target 'dConnectDeviceTheta' do
  pod 'DeviceConnectSDK', podspec: "../../dConnectSDK/dConnectBrowserForIOS9/specs/DeviceConnectSDK.podspec"
end
pre_install do |installer_representation|
  system "sh ./download-lib.sh"
  p "Download libs"
end