# source 'https://github.com/DeviceConnect/DeviceConnect-PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
$targetSource = "https://github.com/TakayukiHoshi1984/DeviceConnect-iOS"

platform :ios, '9.0'
target 'dConnectDeviceChromecast' do
  pod 'google-cast-sdk', '2.10.4.1'
  pod 'DeviceConnectSDK', podspec: "../../dConnectSDK/dConnectBrowserForIOS9/specs/DeviceConnectSDK.podspec"
end
